name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker images
        run: |
          docker build -t khevi/my-resume-from-desktop:${{ github.run_number }} .
          docker build -t khevi/my-resume-from-desktop .

      - name: Log in to DockerHub
        run: echo "${{ secrets.REGISTRY_PASS }}" | docker login -u khevi --password-stdin

      - name: Push Docker images
        run: |
          docker push khevi/my-resume-from-desktop:${{ github.run_number }} 
          docker push khevi/my-resume-from-desktop

  
